name: Trigger auto deployment for contosoair

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/contosoair-AutoDeployTrigger-976fe1f3-83e8-4a40-a073-607569c74ed6.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTOSOAIR_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ca1b3573d1cbacr.azurecr.io
          registryUsername: ${{ secrets.CONTOSOAIR_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTOSOAIR_REGISTRY_PASSWORD }}
          containerAppName: contosoair
          resourceGroup: ivanp_rg_5046
          imageToBuild: ca1b3573d1cbacr.azurecr.io/contosoair:${{ github.sha }}
          

     

